/* Generated by configure */
#include <poll.h>
#include <signal.h>
#include <time.h>
int main(int argc, char **argv)
{
    (void)argc; (void)argv;
    /* BEGIN TEST: */
    struct pollfd pfd;
    struct timespec ts;
    sigset_t sig;
    pollts(&pfd, 1, &ts, &sig);
    /* END TEST */
    return 0;
}
