QT_ARCH = x86_64
QT_BUILDABI = x86_64-little_endian-lp64
QT.global.enabled_features = shared framework debug_and_release rpath build_all c++11 c++14 c99 c11 thread future concurrent
QT.global.disabled_features = cross_compile appstore-compliant c++1z pkg-config force_asserts separate_debug_info simulator_and_device static
QT_CONFIG += shared qt_framework debug_and_release release debug rpath build_all c++11 c++14 concurrent dbus no-pkg-config reduce_exports release_tools stl
CONFIG += shared qt_framework debug
QT_VERSION = 5.12.3
QT_MAJOR_VERSION = 5
QT_MINOR_VERSION = 12
QT_PATCH_VERSION = 3
QT_GCC_MAJOR_VERSION = 4
QT_GCC_MINOR_VERSION = 2
QT_GCC_PATCH_VERSION = 1
QT_MAC_SDK_VERSION = 10.14.4
QT_APPLE_CLANG_MAJOR_VERSION = 10
QT_APPLE_CLANG_MINOR_VERSION = 0
QT_APPLE_CLANG_PATCH_VERSION = 1
QT_EDITION = OpenSource
