/* Generated by configure */
#include <CoreWLAN/CoreWLAN.h>
#include <CoreWLAN/CWInterface.h>
int main(int argc, char **argv)
{
    (void)argc; (void)argv;
    /* BEGIN TEST: */
    [CWInterface interfaceWithName:@"en2"];
    /* END TEST */
    return 0;
}
